FROM ghcr.io/staex-io/cijail-ci:latest

COPY cijail-glibc-2.31.tar.gz /tmp/cijail-glibc-2.31.tar.gz

RUN tar -C /usr/local -xvf /tmp/cijail-glibc-2.31.tar.gz

LABEL org.opencontainers.image.source=https://github.com/staex-io/cijail
LABEL org.opencontainers.image.description="CI test image"

CMD ["/bin/bash"]
