---
name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/staex-io/cijail-ci:latest@sha256:f807e2d40cdd6727e81fc5a1b2ffc223f75a3f2a91b769b65706d413c294d18d
      credentials:
        username: token
        password: ${{ secrets.GHCR_TOKEN }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CIJAIL_ENDPOINTS: 9.9.9.9:53 github.com:443 index.crates.io:443 static.crates.io:443
        pypi.org:443 files.pythonhosted.org:443 lb-140-82-112-4-iad.github.com:443
        lb-140-82-113-3-iad.github.com:443 lb-140-82-114-4-iad.github.com:443 lb-140-82-116-4-sea.github.com:443
        151.101.44.223:443 lb-140-82-113-4-iad.github.com:443
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: DNS
        run: ./ci/dns.sh
      - name: Lint
        run: ./ci/lint.sh
      - name: Test
        run: ./ci/test.sh
      - name: Build
        run: ./ci/binaries.sh
      - name: Release
        run: ./ci/release.sh
