---
name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/staex-io/cijail-ci:latest
      credentials:
        username: token
        password: ${{ secrets.GHCR_TOKEN }}
      options: --cap-add SYS_PTRACE --volume "/var/run/docker.sock:/var/run/docker.sock"
    permissions:
      packages: write
    env:
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CIJAIL_ENDPOINTS: |
        https://github.com/lyz-code/yamlfix/
        https://pypi.org/simple/
        https://files.pythonhosted.org/packages/
        https://static.crates.io/crates/
        https://index.crates.io/
        https://uploads.github.com/repos/staex-io/cijail/releases/
        https://api.github.com/repos/staex-io/cijail/releases
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: DNS
        run: ./ci/dns.sh
      - name: Lint
        run: cijail ./ci/lint.sh
      - name: Cargo deny warm-up
        run: cijail ./ci/cargo-deny-warm-up.sh
      - name: Cargo deny
        run: cargo deny check
      - name: Test
        run: ./ci/test.sh
      - name: Binaries
        run: cijail ./ci/binaries.sh
      - name: Packages
        run: cijail ./ci/packages.sh
      - name: Docker images
        run: ./ci/containers.sh
      - name: Release
        run: cijail ./ci/release.sh
