---
name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/staex-io/cijail-ci:latest@sha256:f807e2d40cdd6727e81fc5a1b2ffc223f75a3f2a91b769b65706d413c294d18d
      credentials:
        username: token
        password: ${{ secrets.GHCR_TOKEN }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CIJAIL_ALLOWED_ENDPOINTS: 9.9.9.9:53 github.com:443 index.crates.io:443
      CIJAIL_ALLOWED_DNS_NAMES: github.com index.crates.io
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: DNS
        run: echo 'nameserver 9.9.9.9' > /etc/resolv.conf
      - name: Lint
        run: cijail ./ci/lint.sh
      - name: Test
        run: cijail ./ci/test.sh
      - name: Build
        run: ./ci/binaries.sh
      - name: Release
        run: ./ci/release.sh
