---
name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/staex-io/cijail-ci:latest@sha256:592e78d4432c1db857cd0e64d6a4c89b5d056358291a5e81b73fd8ee907a14de
      credentials:
        username: token
        password: ${{ secrets.GHCR_TOKEN }}
      options: --cap-add SYS_PTRACE
    env:
      RUST_BACKTRACE: 1
      RUST_TEST_THREADS: 1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CIJAIL_ENDPOINTS: 9.9.9.9:53 github.com:443 index.crates.io:443 static.crates.io:443
        pypi.org:443 files.pythonhosted.org:443 lb-140-82-112-4-iad.github.com:443
        lb-140-82-113-3-iad.github.com:443 lb-140-82-114-4-iad.github.com:443 lb-140-82-116-4-sea.github.com:443
        151.101.44.223:443 lb-140-82-113-4-iad.github.com:443 api.github.com:443 uploads.github.com:443
        lb-140-82-116-14-sea.github.com:443 lb-140-82-112-13-iad.github.com:443 lb-140-82-114-3-iad.github.com:443
        lb-140-82-116-3-sea.github.com:443 lb-140-82-112-3-iad.github.com:443 151.101.130.137:443
        151.101.2.137:443 151.101.66.137:443 151.101.194.137:443
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: DNS
        run: ./ci/dns.sh
      - name: Lint
        run: cijail ./ci/lint.sh
      - name: Test
        run: ./ci/test.sh
      - name: Build
        run: cijail ./ci/binaries.sh
      - name: Release
        run: ./ci/release.sh
