---
name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/staex-io/cijail-ci:latest@sha256:18e2405dc81096478c4227f6ddf08fcdda7c00b8c3df0861b95611acd684d2a8
      credentials:
        username: token
        password: ${{ secrets.GHCR_TOKEN }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        run: ./ci/lint.sh
      - name: Test
        run: ./ci/test.sh
      - name: Build
        run: ./ci/binaries.sh
      - name: Release
        run: ./ci/release.sh
