---
name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/staex-io/cijail:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        run: ./ci/lint.sh
      - name: Test
        run: ./ci/test.sh
