---
name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/staex-io/cijail-ci:latest@sha256:f807e2d40cdd6727e81fc5a1b2ffc223f75a3f2a91b769b65706d413c294d18d
      credentials:
        username: token
        password: ${{ secrets.GHCR_TOKEN }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        run: ./ci/lint.sh
      - name: Test
        run: ./ci/test.sh
      - name: Build
        run: ./ci/binaries.sh
      - name: Release
        run: ./ci/release.sh
